# Generated by Django 3.2.5 on 2021-07-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_url', models.CharField(max_length=512)),
                ('question_title', models.CharField(max_length=64)),
                ('discussions', models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('student_solved_questions', models.ManyToManyField(blank=True, related_name='solved_by', to='baseapp.question')),
            ],
        ),
    ]
